"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var calculateHue_1 = require("./calculateHue");
exports.calculateHue = calculateHue_1.default;
var calculateAlpha_1 = require("./calculateAlpha");
exports.calculateAlpha = calculateAlpha_1.default;
var calculateSV_1 = require("./calculateSV");
exports.calculateSV = calculateSV_1.default;
var calculateSL_1 = require("./calculateSL");
exports.calculateSL = calculateSL_1.default;
var calculateChanges_1 = require("./calculateChanges");
exports.calculateChanges = calculateChanges_1.default;
var clamp_1 = require("./clamp");
exports.clamp = clamp_1.default;
var mapRange_1 = require("./mapRange");
exports.mapRange = mapRange_1.default;
var getRelativeCoords_1 = require("./getRelativeCoords");
exports.getRelativeCoords = getRelativeCoords_1.default;
var getColorFormats_1 = require("./getColorFormats");
exports.getColorFormats = getColorFormats_1.default;
var getColorChanges_1 = require("./getColorChanges");
exports.getColorChanges = getColorChanges_1.default;
var formatColorBySpectrum_1 = require("./formatColorBySpectrum");
exports.formatColorBySpectrum = formatColorBySpectrum_1.default;
